name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint-backend
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: monitor-server
      - name: golangci-lint-frontend
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: control-client
